// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace actividadPractica3.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdFormaPago { get; set; }

    public string NomCliente { get; set; }

    public virtual ICollection<DetalleFactura> DetallesFacturas { get; set; } = new List<DetalleFactura>();

    public virtual TipoPago IdFormaPagoNavigation { get; set; }
}